name: Check Version and Create Release

on:
  push:
    branches:
      - main

jobs:
  publish-on-new-version:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check tags
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Get current tag
        id: get_tag
        run: echo ::set-output name=tag::$(git describe --abbrev=0 --tags)
      
      - name: Read version from jsr.json
        id: read_version
        run: echo ::set-output name=version::$(jq -r '.version' jsr.json)
        
      - name: Compare version with latest tag
        id: compare_versions
        run: |
          if [ "${{ steps.read_version.outputs.version }}" != "${{ steps.get_tag.outputs.tag }}" ]; then
            echo "Version in jsr.json is different from latest tag"
            echo "Creating a new release..."
            echo "::set-output name=create_release::true"
          else
            echo "Version in jsr.json matches the latest tag"
            echo "::set-output name=create_release::false"
          fi
      
      - name: Publish to Deno X
        id: create_release_and_publish_to_denox
        if: steps.compare_versions.outputs.create_release == 'true'
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.read_version.outputs.version }}
          release_name: smartshell-sdk@${{ steps.read_version.outputs.version }}
          body: |
            #### Summary:
            [smartshell-sdk@${{ steps.get_tag.outputs.tag }}...${{ steps.read_version.outputs.version }}](https://github.com/xl-soft/smartshell-sdk/compare/${{ steps.get_tag.outputs.tag }}...${{ steps.read_version.outputs.version }})
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to JSR
        id: publish_to_jsr
        if: steps.compare_versions.outputs.create_release == 'true'
        run: |
          npx jsr publish

